version: "3.8"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      # device: ~/goinfre/data/mariadb
      device: /home/pfalasch/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      # device: ~/goinfre/data/wordpress
      device: /home/pfalasch/data/wordpress
      o : bind
      type : none

networks:
  pit_inception_network:
    name: pit_inception_network

services:
#mariadb
  mariadb:
    image: mariadb:pfalasch
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - pit_inception_network
    restart: always
#nginx
  nginx:
    image: nginx:pfalasch
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    expose:
      - 3306
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - pit_inception_network
    restart: always
#wordpress
  wordpress:
    image: wordpress:pfalasch
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    expose:
      - 9000
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - pit_inception_network
    restart: always
